[package]
name = "repl_framework"
version = "0.3.0"
edition = "2021"
description = "A crate to easily create simple repls"
readme = "README.md"
repository = "https://github.com/SuKiN-a/repl_framework"
license = "GPL-3.0"
keywords = ["repl"]
categories = ["command-line-interface"]
